spring:
  datasource:
    url: jdbc:mysql://localhost:3307/vocab?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: vocab
    password: vocabpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080